apiDomain: "api.ntt.steakholdermeating.com"
apiStorageClass: microk8s-hostpath
apiStorageClassSize: 10Gi
uiDomain: "ntt.steakholdermeating.com"
issuerDomain: "nttdev.us.auth0.com"
clientId: blFghGfwUHOlKwDZzOELBFmxOTkxCeQr
installLoadBalancer: true
mongoStorageClass: microk8s-hostpath
mongoStorageClassSize: 1Gi
certIssuer: letsencrypt-prod
ingressNamespace: "ingress"